#!/bin/sh

#- initramfs や chroot 環境で、まだ /proc がマウントされていないときに実行する
#- QEMU で OS 自作テストするときも、ユーザランドが起動する前に /proc を
#- マウントしておかないと ps や top が動かない
mount -t proc none /proc

# - initramfs や chroot 環境で、まだ /sys がマウントされていないときに実行する
# - udev や systemd が正常に動作するために必要
# - QEMUでのOS自作テストでも、デバイス検出やドライバの挙動を確認するために /sys を
#   マウントしておくと便利
mount -t sysfs none /sys

# - initramfs や chroot 環境で /dev がまだ準備されていないときに実行する
# - udev/systemd が動く前に最低限のデバイスノードを揃えるために必要
# - QEMUでのOS自作テストでも、ユーザランドが /dev を必要とするので、devtmpfs を
# マウントしておくと便利
mount -t devtmpfs none /dev


# 画面にメッセージを表示
echo "Umu Project Emergency Shell"

# シェルを起動して対話モードに入る
exec /bin/sh




