#!/bin/sh
# --- 仮想ファイルシステムのマウント ---
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

CMDLINE="$(cat /proc/cmdline)"

if echo "$CMDLINE" | grep -q "single"; then
  echo "Umu Project Step2: Single-user rescue mode"
  exec /bin/sh
else
  echo "Umu Project Step2: Multi-user mode"
  exec /sbin/getty -L ttyS0 115200 vt100
fi
